### ISSUE TITLE
Optional Objects

### ISSUE THREAD

**Issue by JensRavens** [nerdgeschoss/react-use-form-library#23]
When the form contains an optional object, it should be possible to implicitly create it by assigning one of its properties.

```ts
interface User {
  address?: {
    name?: string 
  }
}
const form = new Form<User>({model: {}});
form.fields.address.name; // should be accessible and return undefined
form.fields.address.name.onChange("Joe"); // should implicitly assign `address` to `{ name: "Joe" }` 
```

**Important**
Do not change the value of the form when accessing the object. This happens during render of React and therefore should never trigger a state update. The only moment to trigger a state update is during the `onChange` function.

**Comment by leoggonzalez** [comment]
This should already be working. There's a even test for it

```
it('updates the value after changing nested fields', () => {
  const form = createForm();
  expect(form.fields.address.value).toEqual(undefined);
  form.fields.address.fields.streetName.onChange('Test Address 123');
  expect(form.fields.address.value.streetName).toEqual('Test Address 123');
});
```
